---
version: "3"
services:
  avatarservice:
    image: "avatarservice"
    build: "AvatarService"
    networks:
    - "mn_bridge_network"
  regionservice:
    image: "regionservice"
    build: "RegionService"
    networks:
    - "mn_bridge_network"
  worldservice:
    image: "worldservice"
    build: "WorldService"
    networks:
    - "mn_bridge_network"
  shopservice:
    image: "shopservice"
    build: "ShopService"
    networks:
    - "mn_bridge_network"
  itemservice:
    image: "itemservice"
    build: "ItemService"
    networks:
    - "mn_bridge_network"
  vehicleservice:
    image: "vehicleservice"
    build: "VehicleService"
    networks:
    - "mn_bridge_network"
  accountservice:
    image: "accountservice"
    build: "Account\\AccountService"
    networks:
    - "mn_bridge_network"
  gatewayservice:
    image: "gatewayservice"
    build: "GatewayService"
    networks:
    - "mn_bridge_network"
  portservice:
    image: "portservice"
    build: "PortService"
    networks:
    - "mn_bridge_network"
networks:
  mn_bridge_network:
    external:
      name: "mn_bridge_network"
