version: "2.1"
services:

# Account Service Definition

  account-service:
    build: 
      context: ./AccountService
      dockerfile: Deploy.Dockerfile
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    links:
      - activemq
      - account-db
    command: "/wait-for-it.sh activemq:61616 -- /wait-for-it.sh account-db:5432 -- java -Xdebug -Xrunjdwp:transport=dt_socket,address=8998,server=y,suspend=n -cp ./target/classes:./target/lib/* ServiceImpl"
    ports:
      - 8998:8998

  account-db:
    build: ./AccountDB

# Message Broker
   
  activemq:
    image: "webcenter/activemq:latest"
    ports:
      - 61616:61616